alert
let userName = prompt('What is your name')
let Restaurant1 = prompt ('list a restaurant')
let FoodItem1 = prompt ('list a food item')
let FoodItem2 = prompt ('list a food item')
let DrinkItem1 = prompt ('list a drink item')
let Adjective1 = prompt ('list an adjective')
let Adjective2 = prompt ('list an adjective ')
let Restaurant2 = prompt ('list a restaurant')
let Restaurant3 = prompt ('list a restaurant')
let FoodItem3 = prompt ('list a food item')
let FoodItem4 = prompt ('list a food item')
let FoodItem5 = prompt ('list a food item')
let FoodItem6 = prompt ('list a food item')
let Restaurant4 = prompt ('list a restaurant')
let Restaurant5 = prompt ('list a restaurant')
let Restaurant6 = prompt ('list a restaurant')
let Restaurant7 = prompt ('list a restaurant')
let Restaurant8 = prompt ('list a restaurant')
let FoodItem7 = prompt ('list a food item')
let FoodItem8 = prompt ('list a food item')
let DrinkItem2 = prompt ('list a drink item')
console.log(userName)
console.log(Restaurant1)
console.log(FoodItem1)
console.log(FoodItem2)
console.log(DrinkItem1)
console.log(Adjective1)
console.log(Restaurant2)
console.log(Restaurant3)
console.log(FoodItem3)
console.log(FoodItem4)
console.log(FoodItem5)
console.log(FoodItem6)
console.log(Restaurant4)
console.log(Restaurant5)
console.log(Restaurant6)
console.log(Restaurant7)
console.log(Restaurant8)
console.log(FoodItem7)
console.log(FoodItem8)
console.log(DrinkItem2)
let myStory = `Hello, ${userName}, we both should go to ${Restaurant1} and order ${FoodItem1}, ${FoodItem2}, ${DrinkItem1}. We should enjoy as much as we can or it would be  ${Adjective1} and  ${Adjective2}. I love eating at ${Restaurant2} a lot more than ${Restaurant3}. I also want to eat a lot of ${FoodItem3} just because it is so amazingly good. if i had to choose between ${FoodItem4} and ${FoodItem5}, it would definitely be ${FoodItem6}. like I said, it is so delicious. The food at ${Restaurant4} is pretty good. but the food at ${Restaurant5} is much better. so that's the end of my story called the food story. never hate on restaurants like ${Restaurant6} and  ${Restaurant7}. I would definitely eat a lot of  ${Restaurant8} just because the food/drink items like  ${FoodItem7}, ${FoodItem8} and ${DrinkItem2} is absolutely amazing and delicious  `
console.log(myStory)
document.getElementById('story').innerHTML = myStory; 
